/* Host tool: bake Inter TTF into ugx_font.inc for freestanding Surface::text. */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#define FONT_H 14
#define FIRST_CH 32
#define LAST_CH 126
#define GLYPH_COUNT (LAST_CH - FIRST_CH + 1)

int main(int argc, char **argv)
{
    const char *ttf_path = argc > 1 ? argv[1] : "assets/fonts/Inter-Regular.ttf";
    const char *out_path = argc > 2 ? argv[2] : "src/user/ugx_font.inc";
    float pixel_height = argc > 3 ? (float)atof(argv[3]) : 13.0f;

    FILE *f = fopen(ttf_path, "rb");
    if (!f) {
        fprintf(stderr, "failed to open %s\n", ttf_path);
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    unsigned char *ttf = (unsigned char *)malloc((size_t)sz);
    if (!ttf || fread(ttf, 1, (size_t)sz, f) != (size_t)sz) {
        fprintf(stderr, "failed to read %s\n", ttf_path);
        return 1;
    }
    fclose(f);

    stbtt_fontinfo font;
    if (!stbtt_InitFont(&font, ttf, stbtt_GetFontOffsetForIndex(ttf, 0))) {
        fprintf(stderr, "stbtt_InitFont failed\n");
        return 1;
    }

    float scale = stbtt_ScaleForPixelHeight(&font, pixel_height);
    int ascent, descent, line_gap;
    stbtt_GetFontVMetrics(&font, &ascent, &descent, &line_gap);
    int baseline = (int)(ascent * scale + 0.5f);
    if (baseline < 1)
        baseline = 1;
    if (baseline > FONT_H - 1)
        baseline = FONT_H - 1;

    FILE *out = fopen(out_path, "w");
    if (!out) {
        fprintf(stderr, "failed to write %s\n", out_path);
        return 1;
    }

    fprintf(out, "/* Auto-generated by tools/bake_ugx_font.c from Inter — do not edit. */\n");
    fprintf(out, "#define UGX_FONT_H %d\n", FONT_H);
    fprintf(out, "#define UGX_FONT_BASELINE %d\n", baseline);
    fprintf(out, "typedef struct ugx_glyph {\n");
    fprintf(out, "    uint8_t  advance;\n");
    fprintf(out, "    uint16_t bits[UGX_FONT_H];\n");
    fprintf(out, "} ugx_glyph;\n\n");
    fprintf(out, "static const ugx_glyph ugx_font[%d] = {\n", GLYPH_COUNT);

    for (int ch = FIRST_CH; ch <= LAST_CH; ch++) {
        int glyph = stbtt_FindGlyphIndex(&font, ch);
        int ax, lsb;
        stbtt_GetGlyphHMetrics(&font, glyph, &ax, &lsb);
        int advance = (int)(ax * scale + 0.5f);
        if (advance < 1)
            advance = 1;
        if (advance > 15)
            advance = 15;

        int x0, y0, x1, y1;
        stbtt_GetGlyphBitmapBox(&font, glyph, scale, scale, &x0, &y0, &x1, &y1);

        int bw = x1 - x0;
        int bh = y1 - y0;
        unsigned char *bitmap = NULL;
        if (bw > 0 && bh > 0) {
            bitmap = (unsigned char *)calloc((size_t)bw * (size_t)bh, 1);
            stbtt_MakeGlyphBitmap(&font, bitmap, bw, bh, bw, scale, scale, glyph);
        }

        uint16_t bits[FONT_H];
        memset(bits, 0, sizeof(bits));

        if (bitmap) {
            for (int sy = 0; sy < bh; sy++) {
                int dy = baseline + y0 + sy;
                if (dy < 0 || dy >= FONT_H)
                    continue;
                for (int sx = 0; sx < bw; sx++) {
                    int dx = x0 + sx;
                    if (dx < 0 || dx >= 16)
                        continue;
                    if (bitmap[sy * bw + sx] >= 128)
                        bits[dy] |= (uint16_t)(1u << dx);
                }
            }
        }

        if (ch == ' ') {
            advance = 4;
            memset(bits, 0, sizeof(bits));
        }

        char label = (char)ch;
        if (ch == '\\' || ch == '\'')
            label = '?';

        fprintf(out, "    { %2d, {", advance);
        for (int row = 0; row < FONT_H; row++)
            fprintf(out, "0x%04X%s", bits[row], row + 1 < FONT_H ? "," : "");
        fprintf(out, "} }, /* %c */\n", label);

        free(bitmap);
    }

    fprintf(out, "};\n");
    fclose(out);
    free(ttf);
    fprintf(stderr, "wrote %s (h=%d baseline=%d)\n", out_path, FONT_H, baseline);
    return 0;
}
